/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Sat May 22 17:46:05 2021.
 */

#include <string.h>

#include "ct.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int ct_heartbeat_ncu_pack(
    uint8_t *dst_p,
    const struct ct_heartbeat_ncu_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->heartbeat_ncu_status, 0u, 0x03u);

    return (1);
}

int ct_heartbeat_ncu_unpack(
    struct ct_heartbeat_ncu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->heartbeat_ncu_status = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    return (0);
}

uint8_t ct_heartbeat_ncu_heartbeat_ncu_status_encode(double value)
{
    return (uint8_t)(value);
}

double ct_heartbeat_ncu_heartbeat_ncu_status_decode(uint8_t value)
{
    return ((double)value);
}

bool ct_heartbeat_ncu_heartbeat_ncu_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int ct_log1_ncu_pack(
    uint8_t *dst_p,
    const struct ct_log1_ncu_t *src_p,
    size_t size)
{
    uint16_t log1_ncu_angle;
    uint16_t log1_ncu_angle_ref;
    uint16_t log1_ncu_drv_vel;
    uint16_t log1_ncu_filt_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    log1_ncu_angle = (uint16_t)src_p->log1_ncu_angle;
    dst_p[0] |= pack_right_shift_u16(log1_ncu_angle, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(log1_ncu_angle, 0u, 0xffu);
    log1_ncu_angle_ref = (uint16_t)src_p->log1_ncu_angle_ref;
    dst_p[2] |= pack_right_shift_u16(log1_ncu_angle_ref, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(log1_ncu_angle_ref, 0u, 0xffu);
    log1_ncu_filt_vel = (uint16_t)src_p->log1_ncu_filt_vel;
    dst_p[4] |= pack_right_shift_u16(log1_ncu_filt_vel, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(log1_ncu_filt_vel, 0u, 0xffu);
    log1_ncu_drv_vel = (uint16_t)src_p->log1_ncu_drv_vel;
    dst_p[6] |= pack_right_shift_u16(log1_ncu_drv_vel, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(log1_ncu_drv_vel, 0u, 0xffu);

    return (8);
}

int ct_log1_ncu_unpack(
    struct ct_log1_ncu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t log1_ncu_angle;
    uint16_t log1_ncu_angle_ref;
    uint16_t log1_ncu_drv_vel;
    uint16_t log1_ncu_filt_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    log1_ncu_angle = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    log1_ncu_angle |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->log1_ncu_angle = (int16_t)log1_ncu_angle;
    log1_ncu_angle_ref = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    log1_ncu_angle_ref |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->log1_ncu_angle_ref = (int16_t)log1_ncu_angle_ref;
    log1_ncu_filt_vel = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    log1_ncu_filt_vel |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->log1_ncu_filt_vel = (int16_t)log1_ncu_filt_vel;
    log1_ncu_drv_vel = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    log1_ncu_drv_vel |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->log1_ncu_drv_vel = (int16_t)log1_ncu_drv_vel;

    return (0);
}

int16_t ct_log1_ncu_log1_ncu_angle_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ct_log1_ncu_log1_ncu_angle_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ct_log1_ncu_log1_ncu_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ct_log1_ncu_log1_ncu_angle_ref_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ct_log1_ncu_log1_ncu_angle_ref_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ct_log1_ncu_log1_ncu_angle_ref_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ct_log1_ncu_log1_ncu_filt_vel_encode(double value)
{
    return (int16_t)(value);
}

double ct_log1_ncu_log1_ncu_filt_vel_decode(int16_t value)
{
    return ((double)value);
}

bool ct_log1_ncu_log1_ncu_filt_vel_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ct_log1_ncu_log1_ncu_drv_vel_encode(double value)
{
    return (int16_t)(value);
}

double ct_log1_ncu_log1_ncu_drv_vel_decode(int16_t value)
{
    return ((double)value);
}

bool ct_log1_ncu_log1_ncu_drv_vel_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
