/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Fri May 28 12:04:34 2021.
 */

#ifndef CT_H
#define CT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CT_HEARTBEAT_PDU_FRAME_ID (0x503u)
#define CT_STATUS12_V_AUTO_FRAME_ID (0x23u)
#define CT_LOG1_PDU_FRAME_ID (0x3c3u)

/* Frame lengths in bytes. */
#define CT_HEARTBEAT_PDU_LENGTH (3u)
#define CT_STATUS12_V_AUTO_LENGTH (1u)
#define CT_LOG1_PDU_LENGTH (8u)

/* Extended or standard frame types. */
#define CT_HEARTBEAT_PDU_IS_EXTENDED (0)
#define CT_STATUS12_V_AUTO_IS_EXTENDED (0)
#define CT_LOG1_PDU_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_STATUS_ER_CHOICE (0u)
#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_STATUS_OK_CHOICE (1u)
#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_STATUS_NC_CHOICE (2u)

#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_SOURCE_NONE_CHOICE (0u)
#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_SOURCE_RCU_CHOICE (1u)
#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_SOURCE_ACU_CHOICE (2u)
#define CT_HEARTBEAT_PDU_HEARTBEAT_PDU_SOURCE_TESTING_CHOICE (3u)

#define CT_STATUS12_V_AUTO_STATUS12_V_AUTO_STATE_OFF_CHOICE (0u)
#define CT_STATUS12_V_AUTO_STATUS12_V_AUTO_STATE_ON_CHOICE (1u)

/**
 * Signals in message heartbeatPDU.
 *
 * All signal values are as on the CAN bus.
 */
struct ct_heartbeat_pdu_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t heartbeat_pdu_status;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t heartbeat_pdu_error_code;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t heartbeat_pdu_source;
};

/**
 * Signals in message status12V_Auto.
 *
 * Status for 12V Auto
 *
 * All signal values are as on the CAN bus.
 */
struct ct_status12_v_auto_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t status12_v_auto_state;
};

/**
 * Signals in message log1PDU.
 *
 * All signal values are as on the CAN bus.
 */
struct ct_log1_pdu_t {
    /**
     * Range: -
     * Scale: 10
     * Offset: 0
     */
    uint16_t log1_pdu_db_ext_current;

    /**
     * Range: -
     * Scale: 10
     * Offset: 0
     */
    uint16_t log1_pdu_db_int_current;

    /**
     * Range: -
     * Scale: 10
     * Offset: 0
     */
    uint16_t log1_pdu_acu_current;

    /**
     * Range: -
     * Scale: 10
     * Offset: 0
     */
    uint16_t log1_pdu_db_int_auto_current;

    /**
     * Range: -
     * Scale: 10
     * Offset: 0
     */
    uint16_t log1_pdu_db_ext_auto_current;

    /**
     * Internal Temperature of PDU
     *
     * Range: -
     * Scale: 2
     * Offset: 0
     */
    uint8_t log1_pdu_int_temp;
};

/**
 * Pack message heartbeatPDU.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ct_heartbeat_pdu_pack(
    uint8_t *dst_p,
    const struct ct_heartbeat_pdu_t *src_p,
    size_t size);

/**
 * Unpack message heartbeatPDU.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ct_heartbeat_pdu_unpack(
    struct ct_heartbeat_pdu_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ct_heartbeat_pdu_heartbeat_pdu_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_heartbeat_pdu_heartbeat_pdu_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_heartbeat_pdu_heartbeat_pdu_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ct_heartbeat_pdu_heartbeat_pdu_error_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_heartbeat_pdu_heartbeat_pdu_error_code_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_heartbeat_pdu_heartbeat_pdu_error_code_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ct_heartbeat_pdu_heartbeat_pdu_source_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_heartbeat_pdu_heartbeat_pdu_source_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_heartbeat_pdu_heartbeat_pdu_source_is_in_range(uint8_t value);

/**
 * Pack message status12V_Auto.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ct_status12_v_auto_pack(
    uint8_t *dst_p,
    const struct ct_status12_v_auto_t *src_p,
    size_t size);

/**
 * Unpack message status12V_Auto.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ct_status12_v_auto_unpack(
    struct ct_status12_v_auto_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ct_status12_v_auto_status12_v_auto_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_status12_v_auto_status12_v_auto_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_status12_v_auto_status12_v_auto_state_is_in_range(uint8_t value);

/**
 * Pack message log1PDU.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ct_log1_pdu_pack(
    uint8_t *dst_p,
    const struct ct_log1_pdu_t *src_p,
    size_t size);

/**
 * Unpack message log1PDU.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ct_log1_pdu_unpack(
    struct ct_log1_pdu_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ct_log1_pdu_log1_pdu_db_ext_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_log1_pdu_log1_pdu_db_ext_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_log1_pdu_log1_pdu_db_ext_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ct_log1_pdu_log1_pdu_db_int_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_log1_pdu_log1_pdu_db_int_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_log1_pdu_log1_pdu_db_int_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ct_log1_pdu_log1_pdu_acu_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_log1_pdu_log1_pdu_acu_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_log1_pdu_log1_pdu_acu_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ct_log1_pdu_log1_pdu_db_int_auto_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_log1_pdu_log1_pdu_db_int_auto_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_log1_pdu_log1_pdu_db_int_auto_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ct_log1_pdu_log1_pdu_db_ext_auto_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_log1_pdu_log1_pdu_db_ext_auto_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_log1_pdu_log1_pdu_db_ext_auto_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ct_log1_pdu_log1_pdu_int_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double ct_log1_pdu_log1_pdu_int_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ct_log1_pdu_log1_pdu_int_temp_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
